### PR TITLE
Create graphs for expidenture & revenue over time

### PR DESCRIPTION
**Pull request by BASIC-Belic**
Create graphs for expidenture & revenue over time
    -State graphs (normalized by starting year)
    -Region graphs (normalized by starting years
    -Two methods to create those graphs using plt & sns

### CODE REVIEW

**Comment by BASIC-Belic** [comment]
Concerns: 

Methods need to be refactored later to pass name of column that has the values to sum & pass transformation_lambda 

I plotted the graphs two ways but the sns graph below has extra values for states (3,4)

image

plt graph is fine: 
image

**Comment by BASIC-Belic** [comment]
Need to fix this warning in my method 
def plot_finances_as_ratio_of_year_one_sns(df, states, years, title_name, region=None) 

image

**Review by apaniagua6 — APPROVED** [review]
Thank you.. looks good!

**Comment by apaniagua6** [comment]
Please merge.

**Comment by apaniagua6** [comment]
Regarding the data API library.

 Tensorflow's and Fast.ai codebase has some good ideas on this:
https://www.srijan.net/blog/building-a-high-performance-data-pipeline-with-tensorflow
https://github.com/tensorflow/transform/blob/master/examples/census_example_v2.py

So at the end we can have library such as:
from educationdata.urban.org import apifetch # gets dataset from urban.org ..apifetch( district, year, ...)
from educationdata.urban.org import normalize # 
from educationdata.urban.org import transform # 
from educationdata.urban.org import merge_df_codebook # merges codebook and dataframe 


The risks with libraries such as these is that the API tends to change depending on the needs of the users.... so laying out the API beforehand is important to prevent major rewrites between versions.

**Comment by apaniagua6** [comment]
Regarding " graph below has extra values for states (3,4)" ..let's create an issue in github and we can setup some time later to do a 1 hour bug groom session.

**Pull request merged**
