### PR TITLE
Add visualization to finance_load_data.ipynb 

### PR DESCRIPTION
**Pull request by BASIC-Belic**
-Add Jupyter notebook for finance_load_data.ipynb and do initial visualization of total fed, state, local revenue through years for the available states and years through the api

#TODO: Add label on side (in millions -> but normalized, so need to set origin as (0, min_rev)
#TODO: connect the dots 
#TODO: more visualizations

-Pull request also contains old changes to data/ for ga and va for data exploration

### CODE REVIEW

**Comment by apaniagua6** [comment]
Taking a look..

**Comment by apaniagua6** [comment]
The finance_load_data.ipynb is looking good but one thing to note is that the initial call to the API returns the first page of JSON. The json result actually contains a  .next key which points to the url of the next page. 

I propose you add a fix  like so:

```
def get_data_frame(url):
    dfs = []
    data = {"next": url}

    while data and data["next"]: 
        print("Fetching data from", data["next"])
        response = urlopen(data["next"])
        data = loads(response.read())
        dfs.append(pd.DataFrame.from_dict(data["results"]))

    if dfs:
        finance_df = pd.concat(dfs, sort=True)
    return finance_df
    
    
myfinance_data = get_data_frame("https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/")
print(myfinance_data)

```

Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=2
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=3
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=4
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=5
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=6
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=7
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=8
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=9
Fetching data from https://educationdata.urban.org/api/v1/school-districts/ccd/finance/2012/?page=10


Once you make the above changes, I think your plots will look more complete and I will consider this PR ready for merging. 

Another thing I would like to mentions is that the code can be refactored using asyncio so we are not in blocking state during our page reads.  http://aosabook.org/en/500L/a-web-crawler-with-asyncio-coroutines.html

Furthermore, it would be nice to  reuse the above code as a general purpose library by changing the function signature to take filters as described in the API documentation: https://educationdata.urban.org/documentation/  Before we turn this code into a general purpose library I think it would be necessary to understand how we are using the API now and in the future. 

ex:

```
Some endpoints require specifiers or disaggregators. For example, for Common Core of Data enrollment, you must specify a grade:

https://educationdata.urban.org/api/v1/schools/ccd/enrollment/2013/grade-3/
In addition, if you would like these data broken down by race, you would access this URL:

https://educationdata.urban.org/api/v1/schools/ccd/enrollment/2013/grade-3/race/
```

def get_data_frame(url, year, filters, ):

**Comment by BASIC-Belic** [comment]
DONE: Added in making the modular function to get all pages of data but specified to get just 3 pages; improved plot 
TODO: async & library method to get the data from the api

**Comment by apaniagua6** [comment]
LGTM please merge

**Comment by BASIC-Belic** [comment]
image

**Pull request merged**
